# Change these first
owner: gamingmithandicap # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Webseite & Forum
    url: https://www.gamingmithandicap.de
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status2.gamhc.de
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Gaming mit Handicap
  introTitle: "Gaming mit Handicap Status"
  introMessage: Dies ist die Status Seite von Gaming mit Handicap, die **Echtzeit-Daten** von unserem [GitHub repository](https://github.com/gamingmithandicap/status) verwendet.
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
