# Change these first
owner: gamingmithandicap # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Webseite
    url: https://www.gamingmithandicap.de
  #- name: TeamSpeak 3 Server
  #  icon: https://raw.githubusercontent.com/gamingmithandicap/status/master/assets/ts3_icon.png
  #  url: server.gamingmithandicap.de
  #  port: 10011
  #  check: "tcp-ping"
  - name: Minecraft Server
    icon: https://raw.githubusercontent.com/gamingmithandicap/status/master/assets/mc_icon.png
    url: mc.gamhc.de
    port: 25565
    check: "tcp-ping"
  - name: FiveM Server
    icon: https://raw.githubusercontent.com/gamingmithandicap/status/master/assets/gta5_icon.png
    url: play.gamhc.de
    port: 30120
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gamingmithandicap.de
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/gamingmithandicap/status/master/assets/logo.png
  favicon: https://raw.githubusercontent.com/gamingmithandicap/status/master/assets/favicon.png
  name: Status - Gaming mit Handicap
  introTitle: "Gaming mit Handicap Status"
  introMessage: Dies ist die Statusseite von Gaming mit Handicap.
  navbar:
    - title: Webseite
      href: https://www.gamingmithandicap.de
    - title: Status
      href: https://status.gamingmithandicap.de
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  url: "Link"
  status: "Status"
  history: "Verlauf"
  responseTimeGraphAlt: "Reaktionszeit-Diagramm"
  responseTime: "Reaktionszeit"
  responseTimeDay: "24-Stunden Reaktionszeit"
  responseTimeWeek: "7-Tage Reaktionszeit"
  responseTimeMonth: "30-Tage Reaktionszeit"
  responseTimeYear: "1-Tag Reaktionszeit"
  uptime: "Verfügbarkeit"
  uptimeDay: "24-Stunden Verfügbarkeit"
  uptimeWeek: "7-Tage Verfügbarkeit"
  uptimeMonth: "30-Tage Verfügbarkeit"
  uptimeYear: "1-Jahr Verfügbarkeit"
  activeIncidents: Aktuelle Vorfälle
  allSystemsOperational: Alle Systeme sind verfügbar
  degradedPerformance: "🟨 Beeinträchtigte Leistung"
  completeOutage: "🟥 Kompletter Ausfall"
  partialOutage: "🟧 Teilweiser Ausfall"
  incidentReport: "Vorfallsbericht #$NUMBER →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Vorfall $NUMBER Einzelheiten
  incidentDetails: Einzelheiten zum Vorfall
  incidentFixed: Behoben
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentResolved: "Behoben: $PAGE ist wieder verfügbar in $POST nach $DURATION Minuten"
  incidentViewOnGitHub: Auf GitHub ansehen und abonnieren
  incidentCommentSummary: Gepostet am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Behoben nach $MINUTES Minuten mit $POSTS Beiträgen
  liveStatus: Live Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Verfügbarkeit
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: 7 Tage Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Online
  down: Offline
  degraded: Degradiert
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer: Diese Seite ist [Open Source](https://github.com/upptime/upptime) und wurde erstellt von [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Anfragen Limit überschritten
  rateLimitExceededIntro: Du hast die Anzahl der Anfragen, die du in einer Stunde ausführen kannst, überschritten. Du musst daher warten, bevor du diese Webseite erneut aufrufen kannst. Alternativ kannst du ein GitHub Personal Access Token hinzufügen, um diese Webseite weiterhin zu nutzen.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Webseite verwendet die GitHub-API, um auf Echtzeitdaten über den Status unserer Webseiten & Dienste zuzugreifen. Standardmäßig lässt GitHub jeder IP-Adresse 60 Anfragen pro Stunde zu, die du verbraucht hast.
  rateLimitExceededErrorHowCanFix: Wie kann ich das Problem beheben?
  rateLimitExceededErrorFix: Du wartest eine Stunde, bis das Limit deiner IP-Adresse wiederhergestellt wird. Alternativ kannst du deinen GitHub Personal Access Token hinzufügen, wodurch du zusätzlich 5.000 Anfragen pro Stunde erhältst.
  rateLimitExceededGeneratePAT: Erfahre, wie du deinen GitHub Personal Access Token generieren kannst.
  rateLimitExceededHasSet: Du hast einen GitHub Personal Access Token gesetzt.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Füge dein Token hier ein
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Beim Versuch, die neuesten Statusdetails abzurufen, ist ein Fehler aufgetreten.
  errorText: Du kannst es in ein paar Augenblicken noch einmal versuchen.
  errorHome: Zur Startseite gehen
  pastScheduledMaintenance: Vergangene geplante Wartung
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Gestartet am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: alle
